version: 2.1

orbs:
  node: circleci/node@4.3.0

commands:
  prevent-redundant-build:
    parameters:
      target-directory:
        type: "string"
        default: "$TARGET_DIRECTORY"
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: |
          NPM_EXISTS=$(npm view @imnotjames/typeorm versions --json | jq --arg VERSION "$(cat << parameters.target-directory >>/VERSION)" 'contains([$VERSION])')
          if [ "$NPM_EXISTS" = "true" ]; then
            echo "Version already exists in NPM, halting..."
            circleci-agent step halt
          fi


jobs:
  clone-typeorm:
    docker:
      - image: circleci/node:12
    environment:
      TARGET_DIRECTORY: "target/typeorm/"
    steps:
      - checkout
      - run: git clone --depth 1 https://github.com/typeorm/typeorm.git "$TARGET_DIRECTORY"
      - persist_to_workspace:
          root: target
          paths:
            - typeorm/

  generate-new-version:
    docker:
      - image: circleci/node:12
    environment:
      TARGET_DIRECTORY: "target/typeorm/"
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: ./new-version.sh "$TARGET_DIRECTORY"
      - persist_to_workspace:
          root: target
          paths:
            - typeorm/

  build:
    docker:
      - image: circleci/node:12
    environment:
      TARGET_DIRECTORY: "target/typeorm/"
    steps:
      - checkout
      - attach_workspace:
          at: target
      - prevent-redundant-build:
          target-directory: "$TARGET_DIRECTORY"
      - node/install-packages:
          app-dir: "target/typeorm/"
      - run: cd "$TARGET_DIRECTORY" && npm run compile
      - persist_to_workspace:
          root: target
          paths:
            - typeorm/

  package:
    docker:
      - image: circleci/node:12
    environment:
      TARGET_DIRECTORY: "target/typeorm/"
    steps:
      - checkout
      - attach_workspace:
          at: target
      - prevent-redundant-build:
          target-directory: "$TARGET_DIRECTORY"
      - run: ./patch-manifest.sh "$TARGET_DIRECTORY"
      - run: cd "$TARGET_DIRECTORY" && npm run package
      - run: mkdir -p target/artifacts && cd target/artifacts/ && npm pack "../../$TARGET_DIRECTORY/build/package/"
      - store_artifacts:
          path: target/artifacts/
      - persist_to_workspace:
          root: target
          paths:
            - artifacts/
            - typeorm/

  publish:
    docker:
      - image: circleci/node:12
    environment:
      TARGET_DIRECTORY: "target/typeorm/"
    steps:
      - checkout
      - attach_workspace:
          at: target
      - prevent-redundant-build:
          target-directory: "$TARGET_DIRECTORY"
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
      - run: npm publish target/artifacts/*.tgz

workflows:
  version: 2
  npm-mirror:
    jobs:
      - clone-typeorm
      - generate-new-version:
          requires:
            - clone-typeorm
      - build:
          requires:
            - generate-new-version
      - package:
          requires:
            - build
      - publish:
          requires:
            - package


  npm-mirror-cron:
    triggers:
      - schedule:
          cron: "0,15,30,45 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - clone-typeorm
      - generate-new-version:
          requires:
            - clone-typeorm
      - build:
          requires:
            - generate-new-version
      - package:
          requires:
            - build
      - publish:
          requires:
            - package
