version: 2.1

orbs:
  node: circleci/node@4.3.0

commands:
  prevent-redundant-build:
    parameters:
      target-directory:
        type: "string"
        default: "target/"
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: |
          PACKAGE_NAME=$(cat << parameters.target-directory >>/typeorm/package.json | jq -r ".name")
          NPM_EXISTS=$(npm view "${PACKAGE_NAME}" versions --json | jq --arg VERSION "$(cat << parameters.target-directory >>/VERSION)" 'contains([$VERSION])')
          if [ "$NPM_EXISTS" = "true" ]; then
            echo "Version already exists in NPM, halting..."
            circleci-agent step halt
          fi


jobs:
  clone-typeorm:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: git clone --depth 1 https://github.com/typeorm/typeorm.git "target/typeorm/"
      - persist_to_workspace:
          root: target
          paths:
            - typeorm/

  generate-new-version:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: ./new-version.sh "target/"
      - persist_to_workspace:
          root: target
          paths:
            - VERSION

  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: target
      - prevent-redundant-build:
          target-directory: "target/"
      - node/install-packages:
          app-dir: "target/typeorm/"
      - run: cd "target/typeorm" && npm run compile
      - persist_to_workspace:
          root: target
          paths:
            - typeorm/

  patch-manifest:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: target
      - prevent-redundant-build:
          target-directory: "target/"
      - run: ./patch-manifest.sh "target/"
      - persist_to_workspace:
          root: target
          paths:
            - typeorm/

  package:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: target
      - prevent-redundant-build:
          target-directory: "target/"
      - node/install-packages:
          app-dir: "target/typeorm/"
      - run: ./patch-version.sh "target/"
      - run: cd "target/typeorm" && npm run package
      - run: mkdir -p target/artifacts && cd target/artifacts/ && npm pack "../../target/typeorm/build/package/"
      - store_artifacts:
          path: target/artifacts/
      - persist_to_workspace:
          root: target
          paths:
            - artifacts/
            - typeorm/

  publish:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: target
      - prevent-redundant-build:
          target-directory: "target/"
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
      - run: npm publish target/artifacts/*.tgz --access public --tag dev

workflows:
  version: 2
  npm-mirror:
    jobs:
      - clone-typeorm
      - generate-new-version:
          requires:
            - clone-typeorm
      - build:
          requires:
            - generate-new-version
      - package:
          requires:
            - build
      #- publish:
          #requires:
            #- package


  npm-mirror-cron:
    triggers:
      - schedule:
          cron: "0,15,30,45 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - clone-typeorm
      - generate-new-version:
          requires:
            - clone-typeorm
      - build:
          requires:
            - generate-new-version
      - package:
          requires:
            - build
      #- publish:
          #requires:
            #- package


  imnotjames-npm-mirror:
    jobs:
      - clone-typeorm
      - generate-new-version:
          requires:
            - clone-typeorm
      - patch-manifest:
          requires:
            - generate-new-version
      - build:
          requires:
            - patch-manifest
      - package:
          requires:
            - build
      - publish:
          requires:
            - package


  imnotjames-npm-mirror-cron:
    triggers:
      - schedule:
          cron: "0,15,30,45 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - clone-typeorm
      - generate-new-version:
          requires:
            - clone-typeorm
      - patch-manifest:
          requires:
            - generate-new-version
      - build:
          requires:
            - patch-manifest
      - package:
          requires:
            - build
      - publish:
          requires:
            - package
